telegram_token: "YOUR_TELEGRAM_BOT_TOKEN_HERE"
whale_threshold_usd: 1000000

rpc_urls:
  infura: "https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"
  alchemy: "https://eth-mainnet.alchemyapi.io/v2/YOUR_ALCHEMY_API_KEY"

nhost:
  api_url: "https://your-nhost-instance.hasura.app/v1/graphql"
  admin_secret: "YOUR_NHOST_ADMIN_SECRET"